### PR TITLE
Keycard-operated doors

### LINKED ISSUE #62: Keycard doors
- [x] keycard item with unlimited uses
 - [x] KeycardDoor prefab
 - [x] keycards can open a list of doors
 - [x] when keycard is used near a matching door, the door is toggled

### PR DESCRIPTION
**Pull request by lilianluong**
Keycard is an item prefab, KeycardDoor is an object prefab. Place both as desired, and in the inspector for the Keycard, add to the list of gameobjects any doors that the keycard should be allowed to open. Keycards can open multiple doors and doors can be opened by multiple keycards, just make sure they're linked via the keycard script lists as necessary.

Didn't actually test with multiple keycards/doors... so if someone can test that it would be great

### CODE REVIEW

**Comment by lilianluong** [comment]
We would also like a sprite for the keycard, right now it is as usual for me a colored polygon

**Review by andi6558 — CHANGES_REQUESTED** [review]
Looks pretty good, I love that a) when the keycard is around the door the edge of the door turns black and b) the button turns darker when stepped on. However, there are somethings I would like to change, in the order of importance:

- [x] It would be better if the keycard can only be used once, since in my mind it is an incentive to get the player go somewhere, multiple times in a level, so in that case a keycard should dissappear after interacting with the door. Along with this change, maybe the keycard door could be non-interactable after being toggled the first time, just to make sure the players don't do dumb things.

 - [x] (Needs further discussion) It would be more smooth if players could just pick up items by walking on them. There is not much reason why not to pick up things, and players could easily pick up their old item by walking onto the old one again. This fixes the problem that playertesters are very confused about the two keys involved in item interaction.
- [x] There would be this UnassignedReferenceException if I make a new scene. Saying the variable dialogueUI of CutsceneController has not been assigned.
- [x] Doors, even without checking "toggle permanently," can only be opened once, closed once, then not interactable anymore. This bug seems to apply to both the keycard door and button door. Though I am unlikely to use doors that are not toggled permanently, it would be better if that is fixed.
- [x] A small ui change could be not displaying the radius of the keycard. The range of the keycard is not very important.
I also added a sprite to the keycard. All of the things mentioned above are tested in the scene dev/KeyCardTest

Great work!

**Comment by JasonLin43212** [comment]
> * [ ]  (Needs further discussion) It would be more smooth if players could just pick up items by walking on them. There is not much reason why not to pick up things, and players could easily pick up their old item by walking onto the old one again. This fixes the problem that playertesters are very confused about the two keys involved in item interaction.

Wouldn't this cause an infinite loop if you keep on picking up the old item and dropping the current item?

**Comment by andi6558** [comment]
> Wouldn't this cause an infinite loop if you keep on picking up the old item and dropping the current item?

Not if it is done correctly, since the player needs to *walk* on them. A lot games have done this by making the player picking up the item when it is walked on, and when they want to pick up the old one (an unlikely scenario), they need to first walk away to be out of contact with the old item, and walk back.

(This is brought up by the instructors when they tested our game)

**Comment by JasonLin43212** [comment]
> * [ ]  Doors, even without checking "toggle permanently," can only be opened once, closed once, then not interactable anymore. This bug seems to apply to both the keycard door and button door. Though I am unlikely to use doors that are not toggled permanently, it would be better if that is fixed.

I do agree with this but it seems like it only applies to the keycard door. The button door can only be opened  once but not closed, which i think is a good thing since we want the players to be able to go through the button door without having both of them constantly standing on the buttons. Unless... we want to have Portal like buttons where we need to drop stuff on top of the buttons....

**Comment by JasonLin43212** [comment]
> * [ ]  It would be better if the keycard can only be used once, since in my mind it is an incentive to get the player go somewhere, multiple times in a level, so in that case a keycard should dissappear after interacting with the door. Along with this change, maybe the keycard door could be non-interactable after being toggled the first time, just to make sure the players don't do dumb things.

I think that the player using a keycard only once might seem weird since a keycard just suddenly breaking after one use doesn't make that much sense. If we don't want players to use a keycard multiple times in a level, then we can just have different colored keycards. 

As a side comment, I'm not sure how cool / uncool this is, but what if we had a 4 way door? (A door at a 4 way intersection and toggling it can enable the players to go on different paths.

**Comment by lilianluong** [comment]
> [ ] There would be this UnassignedReferenceException if I make a new scene. Saying the variable dialogueUI of CutsceneController has not been assigned.

You will want to link this to the "Dialogue Display" child of UI Canvas, which should also be in the UI Canvas prefab.

**Comment by lilianluong** [comment]
There's now an option on the Player prefab called "Pick Items Automatically". If enabled, players can pick up items by running over them. There is one caveat which is they still have to drop items by pressing the pick/drop button, but idk how else to do it. This might only impact things if we add the not-holding-item noise mechanic.

**Comment by JasonLin43212** [comment]
Everything looks good. I think having the button doors just trigger once is good. The auto-picking up feels nice too. It might take some time for players to get used to it tho. I think we should decide which one we actually want to go with so that the tutorial will say the right thing

**Pull request merged**
